server:
  port: ${PORT:4096}
info:
  app:
    name: "am role assignment service"
management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "always"
      enabled: true
      cache:
        time-to-live: 1s
      group:
        readiness:
          include: "db"
    # METRICS ENDPOINT CONFIG
    # Enable the metrics endpoint
    metrics:
      enabled: true
      cache:
        time-to-live: 1s
  endpoints:
    health:
      sensitive: true
    web:
      base-path: /
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /

security:
  anonymousPaths:
    - "/"
    - "/health/**"
    - "/loggers/**"
    - "/am/role-assignments/fetchFlagStatus"
    - "/swagger"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/search/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
    - "/status/health"
    - "/welcome"
    - "/health/liveness"
spring:
  application:
    name: Role Assignment Service
  config:
    import: "optional:configtree:/mnt/secrets/am/"
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jackson:
    default-property-inclusion: NON_NULL
  spring:
    cloud:
      discovery:
        enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        order_by.default_null_ordering: ${DEFAULT_NULL_ORDERING:last}
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
          lob:
            non_contextual_creation: true
        dialect: uk.gov.hmcts.reform.roleassignment.config.RasPostgreSQL9Dialect
  flyway.enabled: ${ENABLE_DB_MIGRATE:true}
  flyway.locations: classpath:db/migration
  flyway.out-of-order: true
  datasource:
    url: jdbc:postgresql://${ROLE_ASSIGNMENT_DB_HOST:localhost}:${ROLE_ASSIGNMENT_DB_PORT:5451}/${ROLE_ASSIGNMENT_DB_NAME:role_assignment}${ROLE_ASSIGNMENT_DB_OPTIONS:?stringtype=unspecified&reWriteBatchedInserts=true}
    username: ${ROLE_ASSIGNMENT_DB_USERNAME:}
    password: ${ROLE_ASSIGNMENT_DB_PASSWORD:}
    properties:
      charSet: UTFh-8
    hikari:
      maximumPoolSize: ${MAX_POOL_SIZE:8}
      poolName: AMHikariCP
      connectionTimeout: ${CONNECTION_TIMEOUT:50000}
      keepAliveTime: ${KEEP_ALIVE_TIME:60000}
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: microservicekey-am-role-assignment-service
            client-secret: ${AM_ROLE_ASSIGNMENT_SERVICE_SECRET:}
  cache:
    type: ${ENABLE_CACHE:}
    cache-names: token, caseId, userToken
    caffeine:
      spec: maximumSize=500,expireAfterWrite=120s
oidc.issuer: ${OIDC_ISSUER_URL:https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts}

idam:
  s2s-auth:
    # AAAAAAAAAAAAAAAA
    totp_secret: ${AM_ROLE_ASSIGNMENT_SERVICE_SECRET:}
    microservice: am_role_assignment_service
    url: ${IDAM_S2S_URL:http://localhost:4502}
  s2s-authorised:
    services: ccd_gw,am_role_assignment_service,am_org_role_mapping_service,am_role_assignment_refresh_batch,xui_webapp,aac_manage_case_assignment,ccd_data,wa_workflow_api,wa_task_management_api,wa_task_monitor,wa_case_event_handler,iac,hmc_cft_hearing_service,ccd_case_disposer,sscs,fis_hmc_api,fpl_case_service,disposer-idam-user,civil_service,prl_cos_api,nfdiv_case_api
  api.url: ${IDAM_USER_URL:http://localhost:5000}
  client:
    id: ${ROLE_ASSIGNMENT_IDAM_CLIENT_ID:am_docker}
    secret: ${ROLE_ASSIGNMENT_IDAM_CLIENT_SECRET:}
    redirect_uri: ${ROLE_ASSIGNMENT_IDAM_REDIRECT_URI:http://localhost:4096/oauth2redirect}
    admin:
      userId: ${ROLE_ASSIGNMENT_IDAM_ADMIN_USERID:}
      secret: ${ROLE_ASSIGNMENT_IDAM_ADMIN_PASSWORD:}
      scope: ${ROLE_ASSIGNMENT_IDAM_ADMIN_SCOPE:openid profile roles authorities}
  apachehttpclient:
    enable: false

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: BASIC
      datastoreclient:
        url: ${CCD_DATA_STORE_URL:http://localhost:4452}
  hystrix:
    enabled: ${ENABLE_FEIGN_HYSTRIX:true}
  httpclient:
    enabled: false
  okhttp:
    enabled: true

swaggerUrl: ${TEST_URL:localhost:4096}
roleAssignmentUrl: ${TEST_URL:http://localhost:4096}

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:pr}
    user: am-${LAUNCH_DARKLY_ENV:local}
  runOnStartup: ${RUN_LD_ON_STARTUP:false}

audit:
  log:
    ignore:
      statues: 404
    enabled: true

roleassignment:
   query:
     size: 20
     sortcolumn: roleName
org :
  request:
    byPassOrgDroolRule: ${BYPASS_ORG_DROOL_RULE:false}

logging.level.uk.gov.hmcts: ${APPLICATION_LOGGING_LEVEL:INFO}

dbFeature:
  flags:
    enable: ${DB_FEATURE_FLAG_ENABLE:}
    disable: ${DB_FEATURE_FLAG_DISABLE:}

dbMigration:
  # When true, the app will run DB migration on startup.
  # Otherwise, it will just check if all migrations have been applied (and fail to start if not).
  runOnStartup: ${RUN_DB_MIGRATION_ON_STARTUP:true}

springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: method
  writer-with-order-by-keys: true
