/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.hmcts.rse..ccd.lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
