version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "cftlib"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
  - package-ecosystem: "gitsubmodule"
    directory: "projects
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
