spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:${wiremock.server.port:5000}/o

idam:
  s2s-auth:
    url: http://localhost:${wiremock.server.port:4502}
  api.url: http://localhost:${wiremock.server.port:5000}
