java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    am:
      secrets:
        - name: am-role-assignment-service-s2s-secret
          alias: AM_ROLE_ASSIGNMENT_SERVICE_SECRET
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: role-assignment-service-IDAM-CLIENT-SECRET
          alias: ROLE_ASSIGNMENT_IDAM_CLIENT_SECRET
        - name: role-assignment-service-IDAM-ADMIN-SECRET
          alias: ROLE_ASSIGNMENT_IDAM_ADMIN_PASSWORD
        - name: role-assignment-service-LD-SDK-KEY
          alias: LD_SDK_KEY
#  overidding dev memory and cpu limits to make it match with standard limits
#  https://github.com/hmcts/chart-java/blob/master/java/values.yaml
  devmemoryRequests: 1024Mi
  devcpuRequests: 250m
  devmemoryLimits: 2048Mi
  devcpuLimits: 1500m

  environment:
    ROLE_ASSIGNMENT_DB_HOST: "{{ .Release.Name }}-postgresql"
    ROLE_ASSIGNMENT_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    ROLE_ASSIGNMENT_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
    ROLE_ASSIGNMENT_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    ROLE_ASSIGNMENT_DB_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    ROLE_ASSIGNMENT_DB_OPTIONS: "?stringtype=unspecified"
    CCD_DATA_STORE_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAUNCH_DARKLY_ENV: pr
    ENABLE_DB_MIGRATE: true
    BYPASS_ORG_DROOL_RULE: true
    RUN_DB_MIGRATION_ON_STARTUP: true
    RUN_LD_ON_STARTUP: true
    APPLICATION_LOGGING_LEVEL: DEBUG
  postgresql:
    enabled: true
    postgresqlPort: 5432
