name: Build

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
