name: Java CI

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
    - name: Az CLI login
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
      with:
        client-id: 82f79201-9a30-4160-b264-7bbed775c7f4
        tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
        allow-no-subscriptions: true
    - name: ACR Login
      run: az acr login --name hmctsprod
    - name: Publish to Maven Local
      run: (cd cftlib; ./gradlew publishToMavenLocal -i)
    - name: Build
      run: (cd cftlib; ./gradlew check -i)
