name: Publish Tag to Azure Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  PublishToAzureArtifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Publish to Azure DevOps Artifacts
        run: |
          (cd cftlib; ./gradlew -i publishToAzureArtifacts)
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash
